GET http://localhost:3000

###

GET http://localhost:3000/3

###

POST http://localhost:3000
Content-Type: application/json

{
    "title": "Test 10",
    "description": "đi làm"
}

###

PATCH http://localhost:3000/5
Content-Type: application/json

{
    "title": "Test 9",
    "description": "lorem ipsum dolor sit amet, consectetur",
    "dueDate": "2024-02-28 10:00:00",
    "isFinished": true
}

###

DELETE http://localhost:3000/5